# Numpy基础学习和使用

## 创建ndarray
接受一切序列型的对象，包括其他数组

In [16]:
import numpy as np
## 列表转换
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print("arr1= " +  arr1.__str__())

## 嵌套序列
data2 =[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print("arr2= " + arr2.__str__())


arr1= [6.  7.5 8.  0.  1. ]
arr2= [[1 2 3 4]
 [5 6 7 8]]


* zero 和 ones 函数可以分别创建指定长度或形状的全0或全1的数组
* empty 可以创建一个没有任何具体数值的数组
* arange 是Python内置 range 的数组版本

In [17]:
print(np.zeros(10))
print(np.ones((3,6)))
print(np.empty((2,3,2))) ## 未初始化的垃圾数据
print(np.arange(5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[ 2.31584178e+077 -2.31584194e+077]
  [ 2.96439388e-323  0.00000000e+000]
  [ 2.12199579e-314  8.75983079e+164]]

 [[ 4.47032376e-090  3.27484543e+179]
  [ 1.29167885e+160  3.29706744e-032]
  [ 3.99910963e+252  8.34402697e-309]]]
[0 1 2 3 4]


### ndarray的数据类型
* 是一个特殊的对象，它含有ndarray数据类型的信息
* np.array会尝试为新建的数组推断出一个较为合适的数据类型，对于随机创建的数组，更倾向于 float64

In [18]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


* 显示转换数据类型
* 注：大精度数据转小精度数据，则会丢失数据，例如浮点数，转整数
* 字符串数组中，如果表示都是数字，也可以用astype将其转换为数值型

In [19]:
arr = np.array([1,2,3,4])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr.dtype)

## 精度转换丢失
float_arr2 = np.array([3.7,-1.2,-2.6,0.5,4.22])
print(float_arr2)
int_arr = float_arr2.astype(np.int32)
print(int_arr)

## 字符串，表示数值
numic_strings = np.array(['1.24','0.68'],dtype=np.string_)
numic_strings.astype(np.float64)
print(numic_strings)

int64
float64
[ 3.7  -1.2  -2.6   0.5   4.22]
[ 3 -1 -2  0  4]
[b'1.24' b'0.68']


### 矢量化运算
可对数据执行批量运算，大小相等的数组之间的任何运算都会将运算应用到元素级

In [21]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr * arr)
print(arr - arr)
print(1/arr)

[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


### 基本索引和切片
索引可以对数组进行数据子集选取

In [28]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
# 对切片赋值
arr[5:8] = 12
print(arr)

arr_slice  = arr[1:4]
print(arr_slice)
arr_slice[1] = 12345
## 数据修改反映到源数组上
print(arr)

arr_slice[:] = 64
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[1 2 3]
[    0     1 12345     3     4    12    12    12     8     9]
[ 0 64 64 64  4 12 12 12  8  9]


> 注意：
* 对切片赋值时，该值会自动传播到整个选区
* 和列表区别在于，数组切片是原始数组的视图，即数据不会被复制，视图上的任何修改都会直接反映到源数组上

对于高阶数组的索引则为低阶数组，例如二维数组中，索引位置上的元素标量，是一维数组

In [29]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(arr2d[2])

# 各元素进行递归访问
print(arr2d[0][2])
# 支持逗号隔开的索引列表
print(arr2d[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
3
3


高级数组操作

In [30]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d[0])
old_value = arr3d[0].copy()
arr3d[0] = 1234
print(arr3d)
arr3d[0] = old_value
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[1234 1234 1234]
  [1234 1234 1234]
  [1234 1234 1234]
  [1234 1234 1234]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


### 切片索引
切片语法和Python列表功能比较类似，同时高维度对象也适用

In [ ]:
arr = np.arange(10)
print(arr[1:4])

print(arr2d[:2])
# 传入多个切
print(arr2d[:2,1:])
# 整数索引和切片混合
print(arr2d[1,2:])
# 只有冒号，表示整个轴
print(arr2d[:,:1])

### 布尔型索引


### 花式索引

### 数组转置和轴对称